#define BUILD_NUMBER 0
#define MEJOR_VERSION  1
#define MINOR_VERSION  0
#define PATCH_NUMBER 0
#define VERSION_STRING "1.0.0.0\0"
#define VERSION_STR_DWORD 1,0,0,0
#define PRODUCT_VER_STRING "3.4\0"
#define PRODUCT_VER_DWORD  3,4,0,0
#define COMMON_PRODUCTNAME "FSTools\0"
#define COMMON_LEGALCOPYRIGHT "Copyright (C) 2015-2022 YAMASHITA Katsuhiro"
