#define BUILD_NUMBER   201
#define MEJOR_VERSION  3
#define MINOR_VERSION  0
#define PATCH_NUMBER 0
#define VERSION_STRING "3.0.201.0\0"
#define VERSION_STR_DWORD 3,0,201,0
#define PRODUCT_VER_STRING "3.0\0"
#define PRODUCT_VER_DWORD  3,0,0,0
#define COMMON_PRODUCTNAME "FSTools\0"
#define COMMON_LEGALCOPYRIGHT "Copyright (C) 2020 YAMASHITA Katsuhiro"
